ialbert/biostar-central

- biostar/server/templates/server_tags/post_body.html
- biostar/server/templatetags/server_tags.py
Hey
Saw issue #302 . Small fix.
One can now see the view count of the post when viewing the question.
> Added view count to post details page.

- biostar/apps/util/html.py
> Link text preserved when the user has provided one

- biostar/server/templates/flatpages/flatpage_edit.html
- biostar/server/templates/post_details.html
- biostar/server/templates/post_edit.html
- biostar/server/templates/user_edit.html
> Fix ckeditor' static path.

- biostar3/tests/client_test_case.py
- biostar3/tests/forum/test_user_views.py
These commits test the Login, Sign Up, User List and Badge List logic.
This raises `user_views.py` to 73% coverage, for #374.
> Test user views

- biostar/forum/ajax.py
- biostar/forum/static/forum.css
- biostar/forum/static/forum.js
- biostar/forum/templates/post_view.html
- biostar/forum/templates/widgets/comment_body.html
- biostar/forum/templates/widgets/menu-header.html
- biostar/forum/templates/widgets/menu-topics.html
- biostar/forum/templates/widgets/post_body.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/urls.py
- biostar/recipes/apps.py
- biostar/recipes/auth.py
- biostar/recipes/forms.py
- biostar/recipes/models.py
- biostar/recipes/static/engine.js
- biostar/recipes/templates/recipe_edit.html
- biostar/recipes/templates/widgets/recipe_code_edit.html
- biostar/recipes/views.py
-- recipe edit is still being refactored and worked on. 
-- refactoring the drag and drop so I handle the parent-child relationship better.
> added drag and drop for comments, refactoring recipe edit ( still being worked on ).  

- biostar/accounts/forms.py
- biostar/accounts/views.py
- biostar/forum/forms.py
- biostar/recipes/ajax.py
- biostar/recipes/api.py
- biostar/recipes/auth.py
- biostar/recipes/decorators.py
- biostar/recipes/forms.py
- biostar/recipes/management/commands/api.py
- biostar/recipes/management/commands/cleanup.py
- biostar/recipes/management/commands/copy.py
- biostar/recipes/management/commands/data.py
- biostar/recipes/models.py
- biostar/recipes/static/engine.css
- biostar/recipes/static/engine.js
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/recipe_edit.html
- biostar/recipes/templates/recipe_list.html
- biostar/recipes/templates/widgets/json_field.html
- biostar/recipes/templates/widgets/preview_download.html
- biostar/recipes/templates/widgets/snippet.html
- biostar/recipes/templates/widgets/template_field.html
- biostar/recipes/urls.py
- biostar/recipes/views.py
> fixed user signup bug; added recipe create; fixed json and template previews; cleaned unnecessary managers from recipes app.

- biostar/__init__.py
- biostar/forum/apps.py
- biostar/recipes/ajax.py
- biostar/recipes/apps.py
- biostar/recipes/auth.py
- biostar/recipes/forms.py
- biostar/recipes/recipes/hello-world.hjson
- biostar/recipes/signals.py
- biostar/recipes/static/engine.css
- biostar/recipes/static/engine.js
- biostar/recipes/templates/project_users.html
- biostar/recipes/templates/recipe_edit.html
- biostar/recipes/templates/recipe_list.html
- biostar/recipes/templates/recipe_run.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/access_form.html
- biostar/recipes/templates/widgets/authorization_required.html
- biostar/recipes/templates/widgets/show_messages.html
- biostar/recipes/templates/widgets/snippet_list.html
- biostar/recipes/templates/widgets/snippet_type.html
- biostar/recipes/test/test_project.py
- biostar/recipes/views.py
- js_tests/tests.html
- js_tests/tests.js
- refactored AJAX functions in recipes 
- cleaned up interface dropdown in recipe edit; 
- moved recipes signals to signals.py; 
- added signal so newly created projects get a starter recipe;  
- trusted users only allowed to run recipes they have access to; 
- refactored manage access interface
> refactored code 

- biostar/__init__.py
- biostar/recipes/static/engine.js
- biostar/recipes/templates/about.html
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/data_view.html
- biostar/recipes/templates/job_list.html
- biostar/recipes/templates/job_view.html
- biostar/recipes/templates/project_info.html
- biostar/recipes/templates/recipe_run.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/directory_list.html
- biostar/recipes/templates/widgets/menubar.html
- biostar/recipes/urls.py
- biostar/recipes/views.py
- bumped version
- took out line numbers from showing in descriptions
-  added about page
- rearrange buttons
> styling changes

- biostar/accounts/views.py
- biostar/forum/ajax.py
- biostar/forum/models.py
- biostar/forum/search.py
- biostar/forum/signals.py
- biostar/forum/static/forum.css
- biostar/forum/templates/widgets/listing.html
- biostar/forum/templates/widgets/menu-header.html
- biostar/forum/templates/widgets/post_user_box.html
- biostar/forum/templatetags/forum_tags.py
- fixed posts and awards display correctly on profile.
- post counts updated with drag and drop actions.
- user name and locations truncated to 50 characters every where but their profile.
- fixed twitter embedding issue.
- ensure contributors list (thread users) has chronological order.
- date on post user box fixed to show users last login.
> fixed issues, worked on phone display

- biostar/forum/forms.py
- biostar/forum/static/forum.css
- biostar/forum/static/forum.js
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/forum_list.html
- biostar/forum/templates/widgets/listing.html
- biostar/forum/templates/widgets/menu-header.html
- biostar/forum/templates/widgets/menu-topics.html
- biostar/forum/templates/widgets/post_tags.html
- biostar/forum/templates/widgets/post_user_line.html
- biostar/forum/templates/widgets/user_icon.html
- biostar/transfer/management/commands/transfer.py
- themes/bioconductor/Makefile
- themes/bioconductor/manage.py
- took out hardcoded paths in bioconductor makefile
- imporoved phone display.
> refactored makefile for bioconductor; worked on phone display.

- biostar/forum/ajax.py
- biostar/forum/documents.py
- biostar/forum/forms.py
- biostar/forum/management/commands/search.py
- biostar/forum/search.py
- biostar/forum/settings.py
- biostar/forum/static/forum.css
- biostar/forum/templates/about.html
- biostar/forum/templates/faq.html
- biostar/forum/templates/widgets/menu-topics.html
- biostar/forum/templates/widgets/pages_elastic_search.html
- biostar/forum/templates/widgets/post_results.html
- biostar/forum/templates/widgets/post_results_elastic.html
- biostar/forum/templates/widgets/similar_posts_elastic.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/urls.py
- biostar/forum/views.py
- conf/pip_requirements.txt
- themes/bioconductor/settings.py
- themes/bioconductor/templates/about.html
- themes/bioconductor/templates/faq.html
- themes/bioconductor/templates/widgets/menu-topics.html
- testing out elastic search and see how it compares, the default is still whoosh. 
- added about page
-added faq page
> added about page, added faq page

- biostar/forum/search.py
- biostar/forum/settings.py
- biostar/forum/static/forum.css
- biostar/forum/views.py
- fixed tests.
- commenting out elastic stuff
> fixed tests

- biostar/accounts/views.py
- biostar/forum/models.py
- biostar/forum/settings.py
- biostar/forum/static/forum.css
- biostar/forum/templates/banners/menu-header.html
- biostar/forum/templates/banners/menu-phone.html
- biostar/forum/templates/community_list.html
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/post_list.html
- biostar/forum/templates/widgets/feed_default.html
- biostar/forum/templates/widgets/filter_dropdown.html
- biostar/forum/templates/widgets/listing.html
- biostar/forum/templates/widgets/pages.html
- biostar/forum/templates/widgets/search_results.html
- biostar/forum/templates/widgets/user_card.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/views.py
- biostar/planet/apps.py
- biostar/planet/settings.py
- biostar/test/pg_test_settings.py
- biostar/test/test_settings.py
- improved phone display for community list
- changed pagination to not display when applying a `limit` to the posts
> worked on phone display and pagination

- biostar/accounts/auth.py
- biostar/accounts/forms.py
- biostar/accounts/models.py
- biostar/accounts/views.py
- biostar/forum/ajax.py
- biostar/forum/auth.py
- biostar/forum/search.py
- biostar/forum/signals.py
- biostar/forum/tasks.py
- biostar/forum/templates/accounts/user_moderate.html
- biostar/forum/templates/accounts/user_profile.html
- biostar/forum/templates/community_list.html
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/post_list.html
- biostar/forum/templates/widgets/feed_default.html
- biostar/forum/templates/widgets/filter_dropdown.html
- biostar/forum/templates/widgets/listing.html
- biostar/forum/templates/widgets/post_user_line.html
- biostar/forum/templates/widgets/user_filter_dropdown.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/urls.py
- biostar/planet/apps.py
- biostar/planet/auth.py
- simplified templates by refactoring repeatedly used parts into a widget ( dropdowns used to filter)  
- testing out vue app, commented out for now.
- took out deactivate user from the forms, made it so reporting a spammer is not mutually exclusive to other moderation actions.  
- fixed bug in planet app
> fixed bug, simplified templates, testing out vue integration, fixed user moderation

- biostar/accounts/models.py
- biostar/accounts/settings.py
- biostar/forum/auth.py
- biostar/forum/static/forum.css
- biostar/forum/templates/banners/menu-topics.html
- biostar/forum/templates/widgets/listing.html
- biostar/forum/templatetags/forum_tags.py
- biostar/settings.py
- added opacity to spam icon
- spam icon shows for low rep users only 
- counts in the menu are now shown using a label instead of coloring the fonts
> added opactity to spam, changed menu counts to be inside of labels. 

- biostar/forum/forms.py
- biostar/forum/models.py
- biostar/forum/signals.py
- biostar/forum/static/forum.css
- biostar/forum/static/forum.js
- biostar/forum/tasks.py
- biostar/forum/templates/forms/answers_form.html
- biostar/forum/templates/forms/help_text.html
- biostar/forum/templates/forms/inplace_form.html
- biostar/forum/templates/new_post.html
- biostar/forum/templates/post_view.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/urls.py
- biostar/forum/views.py
- biostar/recipes/apps.py
- biostar/recipes/static/engine.js
- biostar/recipes/templates/admin_index.html
- biostar/recipes/templates/widgets/directory_list.html
- biostar/recipes/templates/widgets/files_list.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/utils/markdown.py
- contributors.md
- themes/bioconductor/docs/faq.md
- themes/bioconductor/templates/widgets/similar_posts.html
- fixed wmd-button-bar display #535 
- took out html escaping doc pages markdown ( faq, policy, about)
- updated faq page for bioconductor
> fixed button bar; fixed up bioconductor 

- biostar/accounts/views.py
- biostar/recipes/ajax.py
- biostar/recipes/auth.py
- biostar/recipes/decorators.py
- biostar/recipes/static/engine.css
- biostar/recipes/static/engine.js
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/job_list.html
- biostar/recipes/templates/job_view.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/job_elapsed.html
- biostar/recipes/templates/widgets/loading_img.html
- biostar/recipes/templates/widgets/menubar.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/recipes/test/test_project.py
- biostar/recipes/views.py
- biostar/utils/helpers.py
- added new feature so recipes  std out live updates.
- added all projects tab in base_content.html
- took out job coloring 
- fixed recipe, data, and project counts. 
- added more tests for recipes api.
> improved features, refactored interface. 

- biostar/accounts/models.py
- biostar/forum/auth.py
- biostar/forum/management/commands/test_markdown.py
- biostar/forum/markdown.py
- biostar/forum/models.py
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/tests/test_markdown.py
- biostar/forum/views.py
- biostar/logconf.py
- biostar/recipes/middleware.py
- biostar/recipes/static/engine.css
- biostar/recipes/templates/banners/recipe_sidebanner.html
- added object managers to get rid of redundant queries made across files. 
- added more test cases to markdown. Turned parse_block_html=True to ensure unbalanced tags are closed without escaping.
- filtered out spam users from community list.
- cleaned up recipes view.
> added more test cases to markdown. Added object manager to forum.

- biostar/recipes/static/engine.css
- biostar/recipes/static/engine.js
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/test/test_navigation.py
- biostar/recipes/test/test_recipe.py
- biostar/recipes/views.py
- interface preview put in
- tests are passing
> interface preview put in; tests pass

- biostar/forum/ajax.py
- biostar/forum/auth.py
- biostar/forum/forms.py
- biostar/forum/management/commands/index.py
- biostar/forum/management/commands/search.py
- biostar/forum/search.py
- biostar/forum/settings.py
- biostar/forum/signals.py
- biostar/forum/spam.py
- biostar/forum/static/forum.css
- biostar/forum/static/forum.js
- biostar/forum/static/inplace.js
- biostar/forum/templates/forms/field_tags.html
- biostar/forum/templates/forms/form_inplace.html
- biostar/forum/templates/post_view.html
- biostar/forum/templates/search/search_results.html
- biostar/forum/templates/widgets/post_actions.html
- biostar/forum/templates/widgets/post_details.html
- biostar/forum/views.py
- added spam.py to classify spam
- cleaned up inplace form
- tested and fixed up moderation options with close.
- fixed up wmd-bar.
- cleaned up search.py to be useable in spam.py to create indexes and search.
> fix ups and added spam.py

- biostar/forum/ajax.py
- biostar/forum/api.py
- biostar/forum/auth.py
- biostar/forum/management/commands/index.py
- biostar/forum/management/commands/spam.py
- biostar/forum/models.py
- biostar/forum/search.py
- biostar/forum/settings.py
- biostar/forum/signals.py
- biostar/forum/spam.py
- biostar/forum/static/forum.css
- biostar/forum/static/forum.js
- biostar/forum/templates/pages.html
- biostar/forum/templates/post_list.html
- biostar/forum/templates/post_view.html
- biostar/forum/templates/widgets/post_details.html
- biostar/forum/templates/widgets/post_user_box.html
- biostar/forum/templates/widgets/post_user_line.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/urls.py
- biostar/forum/views.py
- added releasing from quarantine option 
- adding api.py
- added mod and admin list to about pages.
- added management command 'spam' to index and test the spam classifier. 
- fix issue #599
> fixed issue , finalized spam post quarantining, adding api.py

- biostar/accounts/models.py
- biostar/forum/ajax.py
- biostar/forum/auth.py
- biostar/forum/management/commands/index.py
- biostar/forum/management/commands/spam.py
- biostar/forum/models.py
- biostar/forum/signals.py
- biostar/forum/spam.py
- biostar/forum/tasks.py
- biostar/forum/templates/search/search_results.html
- biostar/forum/templates/widgets/post_body.html
- biostar/recipes/templates/parts/recipe_interface.html
- cleaning up spam classifier more.
- quarantining done using a spooler with a slight delay
- marking post as spam automatically adds it to the spam index for future cases.
> clean up and put in spam scoring as a task. 

- biostar/forum/forms.py
- biostar/recipes/auth.py
- biostar/recipes/static/engine.css
- biostar/recipes/templates/parts/recipe_interface.html
- buttons in interface preview have the same width
- help text added to interface builder
> small fixes in interface preview

- biostar/accounts/apps.py
- biostar/recipes/ajax.py
- biostar/recipes/static/engine.css
- biostar/recipes/static/engine.js
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/data_list.html
- biostar/recipes/templates/data_view.html
- biostar/recipes/templates/parts/recipe_info.html
- biostar/recipes/templates/project_info.html
- biostar/recipes/templates/recipe_list.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/clipboard.html
- biostar/recipes/templates/widgets/delete_msg.html
- biostar/recipes/templates/widgets/files_list.html
- biostar/recipes/templates/widgets/recipe_details.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/recipes/urls.py
- biostar/recipes/views.py
- copy recipes button moved next to edit. 
- copy/paste message not overlapping with navigation bar.
- create recipe and add data buttons added to project info.
- success message on recipe delete includes a link to undo.
> fix ups in interface

- biostar/accounts/models.py
- biostar/recipes/auth.py
- biostar/recipes/forms.py
- biostar/recipes/models.py
- biostar/recipes/static/engine.css
- biostar/recipes/static/recipes.js
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/base_template.html
- biostar/recipes/templates/data_view.html
- biostar/recipes/templates/job_view.html
- biostar/recipes/templates/recycle_bin.html
- biostar/recipes/templates/widgets/files_list.html
- biostar/recipes/templates/widgets/loading_img.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/recipes/views.py
- recycle bin refactored to a simple list.
- max upload size correctly displaying.
- flash added when recipe code and interface are saved.
- files ordered by name 
- table of contents added to data view
> recycle bin refactored; small fix ups 

- biostar/recipes/settings.py
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/project_info.html
- biostar/recipes/test/test_navigation.py
- biostar/recipes/urls.py
- biostar/recipes/views.py
- project/list/ redirect authenticated users to my/projects/ and anonymous users to project/list/public
- my/projects shows projects user has write access to.
- project/list/public/ shows public projects and projects user has read access to.
> refactor project listing 

- biostar/recipes/forms.py
- biostar/recipes/settings.py
- biostar/recipes/static/engine.js
- user restricted by number of images instead of cumulative size.
> reworked image upload form

- biostar/recipes/templates/data_list.html
- biostar/recipes/templates/data_view.html
- biostar/recipes/templates/widgets/upload_button.html
- biostar/recipes/urls.py
- biostar/recipes/util.py
- biostar/recipes/views.py
- docs/index.rst
- added data download button
- update docs
> added download button 

- Makefile
- biostar/forum/forms.py
- biostar/forum/management/commands/sync.py
- biostar/forum/sync.py
- biostar/server/sync_settings.py
- conf/ansible/Makefile
- working on forum sync
- fix up deploy command for forum
> forum sync updated 

- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/base_listing.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/menubar.html
- biostar/recipes/views.py
- update in actions dropdown 
- removed actions from tabs 
- recipe detail put back into views
> actions dropdown update

- biostar/recipes/ajax.py
- biostar/recipes/auth.py
- biostar/recipes/forms.py
- biostar/recipes/models.py
- biostar/recipes/signals.py
- biostar/recipes/templates/widgets/menubar.html
- biostar/recipes/urls.py
- biostar/recipes/views.py
- removed clone to root cascading.
> remove clones cascading to root

- biostar/recipes/ajax.py
- biostar/recipes/static/engine.js
- biostar/recipes/templates/widgets/files_list.html
- biostar/recipes/templates/widgets/plugins.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/recipes/urls.py
- biostar/recipes/views.py
- plugins added to display html in the job view. Added to embed jupyter notebooks into the page.
> plugins feature added to recipes

- biostar/forum/templates/forum_base.html
- biostar/forum/templates/new_post.html
- biostar/forum/templates/post_view.html
- biostar/recipes/templates/base_template.html
- themes/bioconductor/templates/forum_base.html
Performance Improvements - Minified jquery-ui.js to jquery-ui.min.js
> Performance Improvements - Minify jquery-ui.js to jquery-ui.min.js

- biostar/forum/forms.py
- biostar/forum/static/forum.css
- biostar/forum/templatetags/forum_tags.py
- biostar/recipes/forms.py
- biostar/transfer/management/commands/transfer.py
- themes/bioconductor/templates/widgets/post_message.html
- themes/bioconductor/templates/widgets/posting_msg.html
- clean up transfer, force text removed from post transfer.
- preformatted styling added to style old mailing list posts.
- custom bioconductor posting message.
> work in forum 

- biostar/recipes/ajax.py
- biostar/recipes/api.py
- biostar/recipes/auth.py
- biostar/recipes/test/data/demo.json
- biostar/recipes/test/test_api.py
- biostar/recipes/urls.py
- api tests being added for recipes
> adding tests

- biostar/forum/api.py
- biostar/forum/static/forum.css
- biostar/forum/templates/banners/menu-header.html
- biostar/forum/templates/widgets/post_body.html
- biostar/forum/templates/widgets/post_user_box.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/tests/test_api.py
- biostar/forum/tests/test_navigation.py
- biostar/forum/urls.py
- biostar/recipes/api.py
- biostar/recipes/auth.py
- biostar/recipes/decorators.py
- biostar/recipes/models.py
- biostar/recipes/templates/parts/recipe_code.html
- biostar/recipes/templates/parts/recipe_interface.html
- biostar/recipes/templates/parts/recipe_run.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/test/test_api.py
- biostar/recipes/test/test_navigation.py
- biostar/recipes/test/test_recipe.py
- biostar/recipes/urls.py
- biostar/recipes/views.py
- conf/ansible/hosts.ini
- conf/site/site_settings.py
- themes/bioconductor/static/theme.css
- test coverage up to 80%
__forum__ : 
- css being refactored into root
- logo changed to svg in forum
- post user box refactored to be simpler. 
- api tests added
__recipes__:
- api GET request allowed without tokens on public project
- recipe code download link includes dynamically generated script name.
- api tests added
> updates in forum and recipes; tests being added

- biostar/emailer/management/commands/test_email.py
- biostar/emailer/sender.py
- biostar/emailer/tasks.py
- biostar/forum/forms.py
- biostar/forum/settings.py
- biostar/forum/signals.py
- biostar/forum/tasks.py
- biostar/forum/templates/messages/subscription_email.html
- biostar/forum/templates/messages/watched_tags.html
- biostar/settings.py
- conf/requirements.txt
- themes/bioconductor/settings.py
- themes/bioconductor/static/theme.css
- themes/bioconductor/templates/messages/watched_tags.html
- ascii enforcement taken out of biocondcutor
- mass email enabled 
- `To` field no longer includes all recipients of an email
- mailing_list, notify_followers, and notify_watched_tags using mass mailing option 
- notify watched tags task given it's own template.
> mass mailing added, work on bioconductor theme 

- biostar/accounts/models.py
- biostar/accounts/util.py
- biostar/forum/search.py
- biostar/forum/static/inplace.js
- biostar/forum/templates/forms/form_answers.html
- biostar/forum/templates/forms/form_inplace.html
- biostar/forum/templates/search/search_results.html
- biostar/forum/views.py
- conf/site/site_uwsgi.ini
- themes/bioconductor/static/theme.js
- themes/bioconductor/templates/messages/mailing_list.html
- themes/bioconductor/templates/messages/subscription_email.html
- themes/bioconductor/templates/messages/watched_tags.html
- fix in inplace edits so CTRL + ENTER submits forms
- shortcut keys added to answer forms as well ( CTRL + ENTER to submit and ESC to empty form) 
- took out counts from search results since they do not reflect the latest counts.
- adding sorting to search results.
> fixes and added sorting to search results

- biostar/accounts/apps.py
- biostar/accounts/models.py
- biostar/forum/ajax.py
- biostar/forum/api.py
- biostar/forum/auth.py
- biostar/forum/middleware.py
- biostar/forum/models.py
- biostar/forum/static/inplace.js
- biostar/forum/templates/banners/menu-header.html
- biostar/forum/templates/forms/form_inplace.html
- biostar/forum/templates/widgets/filter_dropdown.html
- biostar/forum/urls.py
- biostar/forum/views.py
- biostar/recipes/api.py
- biostar/recipes/decorators.py
- biostar/recipes/urls.py
- conf/scripts/data-backup.sh
- conf/scripts/data-export.sh
- user uploaded images given custom file name.
- added delete actions for users in forum
- api upload reworked 
- added back up and export scripts
> updates in forum

- biostar/accounts/apps.py
- biostar/forum/api.py
- biostar/forum/settings.py
- biostar/forum/templates/new_post.html
- biostar/recipes/api.py
- biostar/recipes/urls.py
- biostar/settings.py
- biostar/transfer/management/commands/transfer.py
- biostar/transfer/models.py
- conf/ansible/server-install.yml
- conf/scripts/data-migration.sh
- fixing up transfer.py to include user status
- default location on creation of admins made empty instead of server farm
- recipe_api added to recipes app
> update in transfer

- biostar/celery.py
- biostar/forum/management/commands/test_markdown.py
- biostar/forum/markdown.py
- biostar/forum/search.py
- biostar/forum/tasks.py
- biostar/forum/templates/banners/menu-topics.html
- biostar/settings.py
- conf/requirements.txt
- conf/scripts/data-migration.sh
- adding celery to take over tasks, 
- fix indexed posts by making stripping html
> fixes in forum

- biostar/accounts/tasks.py
- biostar/celery.py
- biostar/celeryconf.py
- biostar/forum/middleware.py
- biostar/forum/settings.py
- biostar/forum/tasks.py
- biostar/settings.py
- biostar/utils/decorators.py
- conf/site/site_settings.py
- made tasks module switchable using settings
- update in celery confs
> updates in forum 

- biostar/celery.py
- biostar/forum/static/forum.css
- biostar/forum/tasks.py
- biostar/forum/templates/forum_base.html
- biostar/recipes/api.py
- biostar/recipes/management/commands/import.py
- biostar/recipes/templates/project_info.html
- biostar/utils/decorators.py
- conf/scripts/data-backup.sh
- added import manage command to load recipes api data.
- improving page speeds
> update in recipes

- biostar/forum/api.py
- biostar/forum/static/forum.js
- biostar/forum/templates/accounts/user_profile.html
- biostar/forum/templates/base_view.html
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/new_post.html
- biostar/forum/templates/post_view.html
- biostar/forum/templates/widgets/post_details.html
- biostar/forum/urls.py
- biostar/forum/views.py
- biostar/recipes/api.py
- biostar/recipes/templates/base_content.html
- biostar/recipes/templates/index.html
- biostar/utils/decorators.py
- conf/ansible/server-restart.yml
- conf/site/site_nginx.conf
- themes/bioconductor/templates/base_view.html
- themes/bioconductor/templates/forum_base.html
- render blocking js removed from base template.
- style sheets being used inline. 
- page speed above 85% on mobile and 98% on desktop.
> page speed increased 

- biostar/forum/api.py
- biostar/forum/templates/forum_base.html
- biostar/forum/views.py
- extra template include in forum base.
- bookmarked answers and comments shown in `my bookmarks`
- bioconductor tags api fix up.
> work on forum

- biostar/accounts/signals.py
- biostar/accounts/tasks.py
- biostar/accounts/views.py
- biostar/celeryconf.py
- biostar/forum/management/commands/cleanup.py
- biostar/forum/settings.py
- biostar/forum/signals.py
- biostar/forum/tasks.py
- biostar/forum/templates/tags_list.html
- biostar/forum/views.py
- biostar/settings.py
- biostar/transfer/management/commands/transfer.py
- conf/ansible/hosts.ini
- conf/ansible/server-install.yml
- conf/ansible/server-restart.yml
- conf/ansible/server-setup.yml
- conf/scripts/celery-beat.sh
- conf/scripts/celery-worker.sh
- conf/site/site_supervisor.conf
- tested all tasks to ensure compatibility with celery and uwsgi
- added and tested redis installation and restart to ansible scripts.
- awards given in small amounts at a time in middleware ( amount set in settings.MAX_AWARDS )
- awards migration stopped in transfer.py
> tasks working and tested with celery and uwsgi

- biostar/celeryconf.py
- biostar/forum/management/commands/tasks.py
- biostar/forum/urls.py
- conf/site/README.md
- conf/site/site_uwsgi.ini
- tested celery beat tasks
- added pg_dump
- added docs for production server settings
- added two more settings in uwsgi to mitigate memory leaks
> update in forum.

- biostar/forum/ajax.py
- biostar/forum/signals.py
- biostar/forum/tasks.py
- biostar/forum/templates/accounts/login.html
- biostar/forum/templates/widgets/post_body.html
- bug fix in tags, run .clear() on save instead of remove() to do intended action.
- Wrap tags in post body with <span class='tags'> to enable inplace edit swapping.
> bug fixes.

- biostar/accounts/signals.py
- biostar/forum/auth.py
- biostar/forum/management/commands/index.py
- biostar/forum/middleware.py
- conf/scripts/forum/index.sh
- conf/site/site_nginx.conf
- conf/site/site_supervisor.conf
- conf/site/site_uwsgi.ini
- refactor counts into separate function 
- updates in log names
> small updates

- Makefile
- biostar/accounts/adapter.py
- biostar/forum/auth.py
- biostar/forum/tasks.py
- emails set to verified when social logins used
- awards date changed to post lastedit_date
> small update

- biostar/forum/tests/test_moderate.py
> added users to posts admin

- biostar/forum/templates/banners/menu-community.html
- biostar/forum/templates/widgets/filter_dropdown.html
- biostar/forum/templatetags/forum_tags.py
- biostar/utils/decorators.py
- relative urls built using the request path instead of being hardcoded
> fix in #752

- biostar/forum/ajax.py
- biostar/forum/static/inplace.js
- biostar/forum/templates/widgets/post_body.html
- biostar/forum/views.py
- .tags class, used in inplace editing, was clashing with an already bound javascript call.
- message added when filtering for tags.
> tags fixed on post view

- biostar/forum/static/forum.css
- biostar/forum/templates/post_list.html
- biostar/forum/templates/tags_list.html
- biostar/forum/templates/widgets/post_tags.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/tests/test_navigation.py
- biostar/forum/urls.py
- biostar/forum/views.py
- biostar/planet/views.py
- post_list() functions returns posts instead of render template
- tags have their own views at /tag/<tag>
- every view in forum renders a template.
- cache removed from authenticated post listings ( mytags, bookmarks, etc).
> update in forum views.py

- biostar/forum/ajax.py
- biostar/forum/forms.py
- biostar/forum/models.py
- biostar/forum/static/forum.js
- biostar/forum/static/inplace.js
- biostar/forum/templates/forms/field_tags.html
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/post_list.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/tests/test_ajax.py
- biostar/forum/urls.py
- biostar/forum/views.py
- validating the tags to be alphanumeric with no spaces. 
- tags field does not suggest any tags in dropdown, 
- mathjax taken out.
- ajax edit refactored to use the same form as non ajax views
> updates in tags, mathjax removed

- biostar/__init__.py
- biostar/forum/auth.py
- biostar/forum/forms.py
- biostar/forum/management/commands/tasks.py
- biostar/forum/settings.py
- biostar/forum/static/forum.js
- biostar/forum/templates/banners/menu-community.html
- biostar/forum/templates/banners/menu-phone.html
- biostar/forum/templates/base_view.html
- biostar/forum/templates/forms/field_tags.html
- biostar/forum/templates/forum_base.html
- biostar/forum/templates/widgets/filter_dropdown.html
- biostar/forum/templatetags/forum_tags.py
- biostar/forum/views.py
- themes/bioconductor/settings.py
- themes/bioconductor/static/theme.css
- themes/bioconductor/templates/banners/menu-header.html
- themes/bioconductor/templates/banners/menu-phone.html
- themes/bioconductor/templates/banners/menu-topics.html
- themes/bioconductor/templates/base_view.html
- themes/bioconductor/templates/forum_base.html
- strict tags enable/disable put in settings
- spaces taken out of tags
- fix conflicts that have changed ( menus, links in templates, counts )
> merge with bioconductor

- biostar/accounts/tasks.py
- biostar/forum/management/commands/cleanup.py
- biostar/forum/static/forum.css
- biostar/forum/templates/accounts/login.html
- biostar/forum/templates/message_list.html
- overflow added to inbox
- message bodies created correctly  and deleted on cleanup.
> fixes in messages

- biostar/forum/auth.py
- update instead of save on drag and drop
> fix in #805

- biostar/forum/static/forum.css
- biostar/forum/templates/tags_list.html
- fixed conflicting .tag style used by .tag dropdown
> tags list fixed

- biostar/forum/markdown.py
- biostar/forum/tests/test_markdown.py
- removed repeated call to bleach linkify and added nofollow callback into list of callbacks with embedder.
> fix in bleach linkifiy

- biostar/forum/ajax.py
- biostar/forum/const.py
- biostar/forum/static/forum.js
- biostar/forum/templates/post_view.html
- similar posts cached for a longer time
- whole template cached in ajax 
- repetitive ?uid= key removed
> similar posts put back in

- biostar/forum/search.py
- biostar/forum/templates/base_view.html
- biostar/forum/templates/widgets/similar_posts.html
- biostar/forum/templatetags/forum_tags.py
- biostar/utils/helpers.py
- html2markdown used in similar posts to avoid raw html
> fix in #751

- biostar/forum/ajax.py
- biostar/forum/moderate.py
- biostar/forum/templates/post_list.html
- biostar/forum/templates/post_tags.html
- biostar/forum/templates/post_topic.html
- biostar/forum/views.py
- remove cache from tags and topics
- tags and topics have their own templates
- cutoff tags and topics 
- optimize query in view logs
> remove cache from tags and topics page and have cutoffs

- biostar/accounts/forms.py
- biostar/forum/forms.py
- biostar/forum/static/forum.js
- biostar/forum/templates/accounts/edit_profile.html
- biostar/forum/templates/banners/menu-header.html
- biostar/forum/templates/forms/field_tags.html
- biostar/utils/helpers.py
- watched tags and my tags validated the same way as post tags 
- tags text escaped in forum.js when settings values
> accounts tags validated the same as post tags

- biostar/forum/ajax.py
- biostar/forum/auth.py
- biostar/forum/views.py
- users that wrote top level posts can accept own answers
> fix for issue #828

- Makefile
- biostar/accounts/auth.py
- biostar/accounts/models.py
- biostar/accounts/signals.py
- biostar/accounts/templates/accounts/email_verify_subject.md
- biostar/forum/ajax.py
- biostar/forum/api.py
- biostar/forum/forms.py
- biostar/forum/markdown.py
- biostar/forum/static/forum.js
- biostar/forum/templates/accounts/email_verify.html
- biostar/forum/templates/accounts/email_verify_subject.md
- biostar/forum/templates/accounts/profile_tab.html
- biostar/forum/tests/test_ajax.py
- biostar/forum/urls.py
- themes/bioconductor/docs/forum/faq.md
- themes/bioconductor/templates/accounts/email_verify.html
- themes/bioconductor/templates/accounts/email_verify_subject.md
- themes/bioconductor/templates/forum_base.html
- themes/bioconductor/templates/post_list.html
- fix issue #804, strikethrough works with ~~
- added email disabling for admins
- fix email verification email sent when first signing up
- fixes in bioconductor templates and docs
> closed #804; fixes in bioconductor theme

- Makefile
- biostar/recipes/tasks.py
- conf/ansible/Makefile
- conf/ansible/hosts.ini
- conf/ansible/server-deploy.yml
- conf/ansible/server-install.yml
- conf/ansible/variables.yml
- conf/site/site_settings.py
- added demo server to ansible playbooks
- clean up playbooks
> added demo server

- biostar/forum/ajax.py
- biostar/forum/herald.py
- biostar/forum/signals.py
- biostar/forum/templates/herald/herald_item.html
- biostar/forum/templates/herald/herald_list.html
- only change herald when status is changed
- upcoming and published issues filer for listing
- published links set to chronological order
- declined links removed on publication
> small herald update

- biostar/forum/static/forum.css
- biostar/forum/templates/diff.html
> change in styling

- biostar/forum/static/forum.js
update in preview js, take out prism
> update in js

- biostar/forum/auth.py
- biostar/forum/forms.py
- biostar/forum/models.py
- biostar/forum/templates/widgets/post_actions.html
- conf/requirements.txt
- bump django
- add has_diff field to posts
> adding post field has_diff; django dump

- biostar/forum/scripts/clean-logs.sh
- biostar/forum/scripts/crontab.txt
crontask for cleaning logs added.
> Crontask for logs
