ialbert/biostar-central

- biostar3/forum/ajax.py
- biostar3/forum/auth.py
- biostar3/forum/models.py
- biostar3/forum/templates/post_moderate.html
- biostar3/forum/tests/test_moderation.py
Previously, all post moderation actions were displayed for all
posts. Users could be confused and select actions that are not
possible, and the UI needed to provide hints about restricted
actions.
Additionally, this commit refactors the logic for determining
authorized actions into the Post model. This makes it easier
to test this logic in isolation, and reduces the complexity of
view code.
> Only display authorized post moderation actions

- biostar3/forum/static/site.css
- biostar3/forum/static/style.css
- biostar3/forum/static/style.less
- biostar3/forum/templates/post_list.html
Previously, child posts would show a score of 0, because
thread_score is only tracked for top-level posts. Now use
vote_count for child posts. Additionally, show whether a child
post was accepted rather than the number of answers, which is
meaningless for child posts.
This fixes https://github.com/ialbert/biostar-central/issues/305
> Show individual post score for child posts

- biostar3/forum/ajax.py
- biostar3/forum/auth.py
- biostar3/forum/models.py
- biostar3/forum/templates/user_moderate.html
- biostar3/forum/tests/test_moderation.py
This is a counterpart to the post moderation refactor in
a7af4b92. Now, only show actions that are possible given
the state of the target user and the permissions of the
moderator.
Additionally, this change prevents non-staff from
reinstating banned users, since non-staff cannot ban users.
> Only display authorized user moderation actions

- biostar/server/ajax.py
When a question has multiple accepted answers, un-accepting one of
them would cause the entire question to be marked as not accepted.
Now, confirm that there are no other accepted sibling posts
before marking the question as not accepted.
This backports https://github.com/ialbert/biostar-central/pull/361
> Backport fix for un-accept behavior with multiple accepted answers

- biostar.sh
Previously environment variables would have to be sourced in
a separate command. This introduces needless complexity into
runscripts and pollutes the namespace of the shell when
developing. Now allow the user to specify the environment
file to source from run/ with the -e option.
> Add an option to biostar.sh to source environment variables

- biostar.sh
This option allows sourcing of environment variables directly from
biostar.sh, rather than a separate command that pollutes the shell
namespace and makes runscripts more complex.
Backports https://github.com/ialbert/biostar-central/pull/368 and
https://github.com/ialbert/biostar-central/pull/369
> Backport addition of -e option to biostar.sh

- biostar3/forum/static/site.css
- biostar3/forum/static/site.less
Cleans up a bunch of old/duplicate style declarations for `#userbar` and `#navbar`. Deletes the obsolete `#topics` CSS rules.
The change I was actually trying to make is in the last commit: increase the spacing between the userbar and the content below it, which felt squeezed together.
> CSS changes to userbar and navbar

- biostar3/forum/models.py
- biostar3/forum/templates/post_unit.html
- biostar3/forum/templates/recent_replies.html
- biostar3/forum/templates/templatetags/user_link.html
- biostar3/forum/templates/user_bar.html
- biostar3/forum/templates/user_list.html
- biostar3/forum/templates/user_view.html
- biostar3/forum/templatetags/widgets.py
Previously the user links were manually reproduced in several
different files, in some cases leading to inconsistent results
(mainly bolding of scores). This refactors all such places to
use user_link.
Additionally, the user_marker tag has been eliminated. The
method user.marker replicates its functionality and can be used
outside of view code.
> Refactor views to use user_link everywhere

- docs/deploy.rst
> Correct typo in documentation

- biostar3/tests/utils/test_flatpage.py
- biostar3/utils/flatpage.py
Break out most of the logic in flatpage into the add_one
method, which can be reasonably unit-tested. Add tests
for add_one and parse_metadata.
This puts `biostar3/utils/flatpage.py` over the 70% test threshold established in #374.
> Refactor and test utils/flatpage.py

- biostar3/forum/ajax.py
- biostar3/forum/mailer.py
- biostar3/tests/utils/test_incoming_mail.py
- biostar3/utils/incoming_mail.py
Break logic for consuming emails POSTed to /site/incoming/email/ into
a separate util class and add tests for that class.
Also use the action constant when generating the reply-to address for
outgoing notification mails.
> Refactor and test incoming mail handler

- biostar3/forum/tests/test_client.py
- biostar3/tests/client_test_case.py
Create a class for client testing that can be inherited by
individual client testing classes. This prevents duplication of
setup code in the testing codebase and makes it easier to
organize client testing code functionally.
Also moves the test client itself to an internal attribute used
only by ClientTestCase.get and ClientTestCase.post, removing
duplicate intialization code in every client test.
This is just a refactor.
> Refactor common client testing methods into ClientTestCase

- biostar/apps/posts/views.py
- biostar/settings/base.py
LANGUAGE_DETECTION in the settings file defines a list of supported languages in the detection.
If such list is empty language detection is not done.
The default stays as it was (english only)
> Added language detection configuration.

- biostar/accounts/models.py
- biostar/accounts/settings.py
- biostar/accounts/views.py
- biostar/recipes/admin.py
- biostar/recipes/factory.py
- biostar/recipes/forms.py
- biostar/recipes/settings.py
- biostar/recipes/static/engine.css
- biostar/recipes/templates/project_list.html
- biostar/recipes/templates/recipe_edit.html
- biostar/recipes/templates/recipe_run.html
- biostar/recipes/templates/recipe_view.html
- biostar/recipes/templates/widgets/access_form.html
- biostar/recipes/templates/widgets/list_view.html
- biostar/recipes/templates/widgets/recipe_details.html
- biostar/recipes/templates/widgets/recipe_form.html
- biostar/recipes/templatetags/engine_tags.py
- biostar/recipes/test/test_project.py
- biostar/recipes/views.py
- show type in recipe data label.
- user status shows in manage access view.
- all user, including owner and current user, with access are displayed in manage access view.
- recipes with clones can not be deleted.
- added `root` field to recipe admin page.
- all recipe edit forms increased in width. 
- trusted users get can see import tab.
-  recipe name shown on edit ( similar to recipe run ).
- trusted users and admin get a higher upload limit.
> improved recipe edit and manage access pages

- Makefile
- biostar/server/urls.py
- biostar/settings.py
-  Environment variables correctly set in makefile.
DATABASE_NAME always created in export/db/: 
Ensures `reset` always deletes inside of export/db/ and the dangerous action `rm -rf  ${DATABASE_NAME}` is replaced with `rm -rf  export/db/${DATABASE_NAME}`.
> fixes in makefile 

- biostar/recipes/static/engine.css
- biostar/recipes/static/recipes.js
- biostar/recipes/templates/base_template.html
- biostar/recipes/templates/parts/recipe_code.html
- biostar/recipes/templates/recipe_view.html
- fix page dragging when clicking recipes, recipe info loaded by default.
- content on wide screens ( 1400px or above ) given side padding to narrow the field of vision.
> fix in page dragging when clicking recipe; content tightened up on wider screens

- biostar/forum/signals.py
- biostar/recipes/models.py
- biostar/recipes/signals.py
- corrected off-by-one-error in recipe count on the project creation.
- all posts by spammers now labeled as spam.
> fix issue with recipe count on project creation 

- biostar/recipes/static/engine.css
- biostar/recipes/templates/base_template.html
- biostar/recipes/templates/widgets/menubar.html
- id=recipe_search was wrongfully being used by both javascript functions and the css, removing it to fix the css broke the javascript calls.
> fix search in recipes

- conf/defaults.env
The subject says it. New "master" branch probably moves away from shell scripts in favor of an ansible-based install, but for those who want to install the "oldstable" version, this `#!/bin/sh` could be a little misleading.
( Basically if sourced though any default system `/bin/sh` replacement, export may not work properly, and therefore starting wsgi app may fail with an unhelpful error _"'DJANGO_SETTINGS_MODULE' environment variable must be set"_ )
> "export VAR=value" is bash syntax ( not sh-portable )

- biostar/forum/markdown.py
ALLOWED_TAGS missing commas between h2 and h3 tag causing a parsing error in those tags.
> ALLOWED_TAGS missing commas between h2 and h3 tag.

- biostar/forum/templatetags/forum_tags.py
Because `forum/templates/forms/forum_errors.html` tries to unpack 3 values any non-field error of the form `raise ValidationError("<message>")` will throw an error saying "Not enough values to unpack."
Adding an extra empty string fixes this.
> Fix bug with non-field related errors

- biostar/emailer/models.py
The attribute "list" is not on the objects, so the emailer subscriptions tab in the admin section consistently fails.
One question, though: what is this emailer section for? You generate 2000 some random fake email addresses and subscriptions and groups and I'm not really sure as to why. Is it for testing? Plus, there's the separate mailer section. Not really sure what the difference between mailer and emailer is.
Thanks!
> Fix __str__ bug on emailer.models.Subscription

- biostar/emailer/sender.py
I saw that all the emails were text-based and I wanted to get html, so I short-circuited the `if len(html) > 10` switch in the EmailTemplate.send_mass to test it and found a couple bugs.
1. `to` in `EmailMultiAlternatives` needs to be a list or tuple
2. `attach_alternative` doesn't return anything, so the result was it was passing an array of None's to send_messages
3. It complained about having a map instead of a list.
With these 3 changes I could get mass html emails through digest/mailing list.
> Fix mass_html_email bug
